#!/bun/bash
DATA_PATH="data"
if [ -z $1 ]
then
  echo "Get the original images URLs from the local data rss folder generated by download_rss_pages.sh and create a txt file"
  echo "Usage: extract_image_urls_from_local_rss.sh [first_page_id] [last_page_id]"
else
  STEP=$1
  mkdir -p "$DATA_PATH/txt"
  rm "$DATA_PATH/txt/original_images_urls.txt"
  while [ $STEP -le $2 ]
  do
    echo "Getting album $STEP..."
    `grep "wp-content\/uploads" $DATA_PATH/rss/pages/$STEP/* | sed s/".*wp-content\/uploads"/"http\:\/\/www\.imagens\.usp\.br\/wp-content\/uploads"/ | sed s/"-[0-9][0-9][0-9]*x[0-9][0-9][0-9]*\.jpg.*"/"\.jpg"/ >> "$DATA_PATH/txt/original_images_urls.txt"`
    ((STEP++))
  done
  echo "to download all pictures use wget -i with the generated txt file"
fi